const items = [
    {
        id: '001',
        image: '../assets/banner1.png',
        company: 'Sangria',
        item_name: 'Floral Printed Handbagss',
        original_price: 3599,
        current_price: 683,
        discount_percentage: 81,
        return_period: 14,
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: '../assets/banner2.png',
        company: 'JOKER & WITCH',
        item_name: 'Unisex Wesley & Buttercup Couple Watches Gift Set JWCW218',
        original_price: 7399,
        current_price: 1479,
        discount_percentage: 80,
        return_period: 14,
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: '../assets/banner3.png',
        company: 'Sztori',
        item_name: 'Classic Short Sleeves Spread Collar Cotton Opaque Printed Casual Shirt',
        original_price: 2298,
        current_price: 919,
        discount_percentage: 60,
        return_period: 14,
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: '../assets/banner4.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14845,
        discount_percentage: 1,
        return_period: 14,
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: '../assets/banner5.png',
        company: 'Ikonic',
        item_name: 'Me Black Beauty Ceramic Coated Floating Plates Hair Iron Straightener - Black',
        original_price: 1450,
        current_price: 1000,
        discount_percentage: 31,
        return_period: 14,
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: '../assets/banner6.png',
        company: 'Bombay Shaving Company',
        item_name: 'Men Blue Classic Beard Trimmer With 4 Blades BTBL899',
        original_price: 899,
        current_price: 799,
        discount_percentage: 11,
        return_period: 14,
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '../assets/banner7.png',
        company: 'THE MAN COMPANY',
        item_name: 'Blanc Classic Duo - Eau De Toilette 50 ml & Body Parfum 120 ml',
        original_price: 1298,
        current_price: 584,
        discount_percentage: 50,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: '../assets/banner8.png',
        company: 'HRX by Hrithik Roshan',
        item_name: 'Boys Typography Printed T-shirt',
        original_price: 799,
        current_price: 383,
        discount_percentage: 52,
        return_period: 14,
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '009',
        image: '../assets/banner9.png',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '010',
        image: '../assets/banner10.png',
        company: 'Afast',
        item_name: 'Gold Toned Textured Contemporary Glass Ceiling Lamp',
        original_price: 2554,
        current_price: 766,
        discount_percentage: 70,
        return_period: 14,
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
    
];